### ISSUE TITLE
[Enhancement] Improve compatibility by using a kernel getter

### ISSUE THREAD

**Issue by ParticleMon** [teleshoes/tpacpi-bat#100]
As kernel methods can return battery stats whether or not tpacpi-bat can, how about making tpacpi-bat's getters use another method, such as based on one discussed here?:
https://www.2daygeek.com/check-laptop-battery-status-and-charging-state-in-linux-terminal/

Because the current getters of tpacpi-bat do not work on my model, I created my own getters by parsing the output of one of these methods.

Inspired by the idea of a monitoring script as a workaround (https://github.com/teleshoes/tpacpi-bat/issues/98#issuecomment-495965663) and based on recommendations for optimal battery life, I'm working on a script/service to adjust dynamically charge or discharge rather than simply holding the charge at SP when plugged in--or is this not a good idea? Is it better to let it hold the charge at SP?

A few questions:
* For the Supported Hardware page, since the setters work on the X380 Yoga but the getters do not, should tpacpi-bat be listed as working or partially working?

* When the battery is at SP, the reported battery level gradually decreases one percent at a time as OS uptime increases. Is this normal?

* When toggling IC together with FD, it seems that IC needs to be toggled before FD; otherwise, FD doesn't seem to be toggled. Is anything more known about the "mysterious" setting of IC? What is its purpose? When should it be used, if ever?

**Comment by teleshoes** [comment]
hmm? this tool has a very very narrow purpose, specifically to expose and document the hidden, undocumented thinkpad acpi battery controlling interface (the one that more or less replaced the SMAPI interface).

i understand that you want a single power-controlling framework that does everything you need, but thats not what this tool is. TLP, on the other hand (which i do not own, use, or control) seems to be exactly the sort of one-stop-shop you want, and has active support and a user base.


`should tpacpi-bat be listed as working or partially working?`
dunno. i dont have such a machine, and i just have to take the advice of users that DO have one


`the reported battery level gradually decreases one percent`
could be a hw problem (e.g.: insufficient power supplied the ac adapter), or an implementation defect in the firmware. (it could also be normal behavior; bear in mind that SP is about charging, not discharging).

`Is anything more known about the "mysterious" setting of IC?`
inhibit-charge has some bizarre behaviors that differs between models. documenting exact behavior is too large a task for me, especially with only a handful of thinkpad models on hand that use this interface.
as for its INTENDED purpose, it is to stop charging the battery explicitly (as opposed to when pct reaches a certain threshold). useful if you want to charge one battery instead of another, or only charge during off-peak electricity hours or something.
