### ISSUE TITLE
Can't install on Fedora 22/23

### ISSUE THREAD

**Issue by AOtterhall** [teleshoes/tpacpi-bat#65]
tpacpi-bat can't be installed on Fedora 22 and 23 systems. I should have all the development tools installed. I'm running kernel version `4.2.6-301` with a `64-bit` system. The following is the output after running `perl ./install.pl`.

``` bash
sudo cp tpacpi-bat /usr/bin [insert password]
git fetch
git reset HEAD --hard
HEAD is now at 89c9c18 fix for kernel 3.17: include linux/acpi.h instead of acpi/acpi.h
git clean -fd
git checkout 3.17
HEAD is now at 89c9c18... fix for kernel 3.17: include linux/acpi.h instead of acpi/acpi.h
make
make -C /lib/modules/4.2.6-301.fc23.x86_64/build M=/tmp/acpi_call modules
make[1]: *** /lib/modules/4.2.6-301.fc23.x86_64/build: No such file or directory.  Stop.
make: *** [default] Error 2
Makefile:8: recipe for target 'default' failed
error running 'make'
```

**Comment by teleshoes** [comment]
that sucks. the problem youre having is with installing acpi_call, a core dependency of tpacpi-bat.

i forked this on github in order to patch it occasionally, but i do not own the project nor am i going to be much help in diagnosing any problems with it. try installing the original directly, and barring that, check out the GUI marcoDallas made.

my fork: https://github.com/teleshoes/acpi_call
original:  https://github.com/mkottman/acpi_call
fedora-specific GUI: https://github.com/marcoDallas/acpi_call_GUI_systemd
