### ISSUE TITLE
ThinkPad T440s

### ISSUE THREAD

**Issue by denisoster** [teleshoes/tpacpi-bat#86]
Please add ThinkPad T440s

**Comment by teleshoes** [comment]
do you mean that you tested it on T440s and it works? if so, feel free to add it to the wiki:
https://github.com/teleshoes/tpacpi-bat/wiki/Supported-Hardware

(if you mean: 'please support the T440s, it doesnt work right', i dont have one and probably wouldnt be able to do anything wth it if i did. however, since models a year before and a year after work, its likely that T440s does too)

thanks
