### ISSUE TITLE
Peak shift clarification

### ISSUE THREAD

**Issue by stiefel40k** [teleshoes/tpacpi-bat#87]
Hi,

so I was installing this tool and I saw in the help this line `Set peak shift state, which is mysterious and inhibits charge`.

I was looking around the internet, and found [this article](http://blog.lenovo.com/en/blog/peak-shift-with-power-manager).

TLDR;
This feature was basically planned for companies and things like that to 
> distribute the power source schedule throughout the company.

And it is pretty neat if you have planned blackouts like it was in Japan after the Tohoku Earthquake.

So yes, this is not a bug issue or something, just a clarification.

**Comment by teleshoes** [comment]
thanks for the article post.
however, the thing which is mysterious is the way in which it differs from inhibitCharge, and what it actually does.

the timing/control of when 'peak shift' occurs happens in userspace; afaict, things like days of the week and time of day are not part of the interface. this begs the question of why PSS is part of the interface, instead of just using BIC.
perhaps they just wanted an exact copy of BIC so that the settings didnt overlap, but we dont know and probably never will.
